import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "bn";

interface LanguageContextType {
  lang: Language;
  toggle: () => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.services": "Services",
    "nav.about": "About",
    "nav.doctor": "Doctor",
    "nav.contact": "Contact",
    "nav.book": "Book Appointment",
    "nav.subtitle": "Dr. Foysal Kabir",

    // Hero
    "hero.badge": "BVC Reg. No. 9774 · Always Open",
    "hero.title": "Vet Consult",
    "hero.degree": "B.Sc. Vet. Sci. & A.H. (SAU) | MS. Fellow in Surgery (SAU)",
    "hero.role": "Registered Veterinary Practitioner · Consultant & Surgeon for Pet Animals",
    "hero.desc": "Expert veterinary consultation, surgery, and comprehensive pet care for your beloved animals. Located in Mohammadpur, Dhaka — always open for your pets' needs.",
    "hero.book": "📅 Book Appointment",
    "hero.whatsapp": "💬 WhatsApp Us",
    "hero.open": "Always Open",
    "hero.location": "Mohammadpur, Dhaka",
    "hero.surgery": "Surgery & Consultation",
    "hero.online": "Online Consult Available",

    // Services
    "services.badge": "Our Services",
    "services.title1": "Expert Care for",
    "services.title2": "Every Pet",
    "services.desc": "From routine check-ups to complex surgeries — professional veterinary care you can trust for your beloved animals.",
    "services.also": "Also Available",
    "services.book": "Book Now →",
    "s1.title": "General Consultation",
    "s1.desc": "Comprehensive health examination for dogs, cats, and other pet animals. Diagnosis and treatment of illnesses, injuries, and chronic conditions.",
    "s1.badge": "Most Popular",
    "s2.title": "Surgery & Operations",
    "s2.desc": "Expert surgical procedures by Dr. Foysal Kabir (MS Fellow in Surgery). Soft tissue surgeries, orthopaedic procedures, and emergency operations.",
    "s3.title": "Vaccination & Prevention",
    "s3.desc": "Complete vaccination schedules for dogs and cats. Anti-rabies, distemper, parvovirus, and all essential preventive immunizations.",
    "s4.title": "Online Consultation",
    "s4.desc": "Can't visit the clinic? Get expert vet advice online via WhatsApp or phone call. Quick diagnosis and prescription for your pet from anywhere in Bangladesh.",
    "s4.badge": "Available Now",
    "extra.dental": "Dental Care",
    "extra.xray": "X-Ray & Imaging",
    "extra.deworm": "Deworming",
    "extra.neuter": "Neutering / Spaying",
    "extra.wound": "Wound Care",
    "extra.lab": "Lab Tests",

    // Why Us
    "why.badge": "Why Vet Consult?",
    "why.title1": "Compassionate Care,",
    "why.title2": "Expert Hands",
    "why.p1": "Vet Consult is a dedicated veterinary practice in Mohammadpur, Dhaka. Led by Dr. Foysal Kabir, we combine clinical expertise with genuine love for animals to provide the best possible outcomes for your pets.",
    "why.p2": "Whether it's a routine vaccination, an emergency surgery, or an online consultation — we are always here for you and your animal family.",
    "why.cta1": "Book a Consultation →",
    "why.cta2": "💬 WhatsApp",
    "why.r1.title": "Always Open",
    "why.r1.desc": "Our clinic is open 24/7 — because emergencies don't follow office hours. Your pet's health is our priority at all times.",
    "why.r2.title": "Qualified Surgeon",
    "why.r2.desc": "Dr. Foysal Kabir holds an MS Fellowship in Surgery from SAU, bringing specialist-level surgical expertise to your pet's care.",
    "why.r3.title": "Registered Practitioner",
    "why.r3.desc": "BVC Registered (Reg. No. 9774) — legally certified and held to the highest professional veterinary standards in Bangladesh.",
    "why.r4.title": "Online Consultations",
    "why.r4.desc": "Get expert vet advice from anywhere in Bangladesh via WhatsApp, phone call, or video — convenient and affordable.",
    "why.r5.title": "All Pet Animals",
    "why.r5.desc": "We care for dogs, cats, rabbits, birds, and more. Every animal deserves professional medical attention.",
    "why.r6.title": "Full Treatment",
    "why.r6.desc": "From routine check-ups and vaccinations to complex surgeries — complete veterinary care under one roof.",

    // Doctor
    "doc.badge": "Meet the Doctor",
    "doc.title1": "Your Pet's",
    "doc.title2": "Trusted Expert",
    "doc.name": "DR. Foysal Kabir",
    "doc.role": "Consultant & Surgeon — Vet Consult",
    "doc.c1": "B.Sc. Vet. Sci. & A. H. — Sher-e-Bangla Agricultural University (SAU)",
    "doc.c2": "MS. Fellow in Surgery — Sher-e-Bangla Agricultural University (SAU)",
    "doc.c3": "Registered Veterinary Practitioner · BVC Reg. No. 9774",
    "doc.c4": "Specialist in Companion Animal Medicine & Surgery (Dogs, Cats & More)",
    "doc.about": "Dr. Foysal Kabir brings deep expertise in veterinary medicine and surgery to every patient. With a passion for animal welfare and a commitment to evidence-based treatment, he has helped hundreds of pet owners in Dhaka ensure their companions live healthy, happy lives. His clinic is always open — because pets can't wait.",
    "doc.wa": "💬 WhatsApp Dr. Foysal",
    "doc.book": "📅 Book a Visit",

    // Testimonials
    "test.badge": "Testimonials",
    "test.title1": "Happy Pets,",
    "test.title2": "Happy Owners",
    "test.desc": "What pet owners in Dhaka say about Dr. Foysal Kabir and Vet Consult.",
    "t1.name": "Rahim U.",
    "t1.pet": "Owner of Tommy (Dog)",
    "t1.text": "Dr. Foysal treated my Labrador Tommy after a serious infection. He was thorough, caring, and always available on WhatsApp for follow-up questions. Highly recommended!",
    "t2.name": "Nusrat J.",
    "t2.pet": "Owner of Mitthu (Cat)",
    "t2.text": "My cat had a complicated surgery and Dr. Foysal performed it brilliantly. The clinic is clean, the doctor is professional, and the 24/7 availability gives so much peace of mind.",
    "t3.name": "Arif H.",
    "t3.pet": "Owner of Bruno (Dog)",
    "t3.text": "Best vet in Mohammadpur without question. Bruno's vaccination and deworming schedule is always handled perfectly. The online consultation option is a game-changer for busy days.",
    "t4.name": "Fatema K.",
    "t4.pet": "Owner of Mimi (Cat)",
    "t4.text": "Dr. Foysal is genuinely passionate about animal welfare. He explains everything clearly and never rushes. Mimi is always in the best hands here.",
    "t5.name": "Tanvir A.",
    "t5.pet": "Owner of Rex (Dog)",
    "t5.text": "I called at midnight for an emergency and Dr. Foysal responded immediately. This level of dedication is rare. Rex recovered fully thanks to his expert care.",
    "t6.name": "Sadia I.",
    "t6.pet": "Owner of Kiki (Bird)",
    "t6.text": "One of the few vets in Dhaka who treats birds properly. Kiki's health has improved significantly under Dr. Foysal's care. Truly a comprehensive pet clinic.",

    // Contact
    "contact.badge": "Visit / Contact Us",
    "contact.title1": "We're",
    "contact.title2": "Always Open",
    "contact.desc": "Walk in anytime or book an appointment in advance. For urgent cases, please call or WhatsApp directly — we respond quickly.",
    "contact.addr.label": "Address",
    "contact.addr.value": "10/7, Block-A, Iqbal Road (Opposite to Holy Flower School), 1st Floor of Green Homes, Flat A-2, Mohammadpur, Dhaka-1207",
    "contact.phone.label": "Phone",
    "contact.alt.label": "Alternate",
    "contact.wa.label": "WhatsApp",
    "contact.email.label": "Email",
    "contact.hours.label": "Hours",
    "contact.hours.value": "Always Open — 24/7",
    "contact.fb": "Follow on Facebook",
    "form.title": "Book an Appointment",
    "form.desc": "Fill in the form and we'll confirm your visit promptly.",
    "form.name": "Your Name *",
    "form.name.ph": "Your full name",
    "form.phone": "Phone / WhatsApp *",
    "form.phone.ph": "01XXXXXXXXX",
    "form.petname": "Pet's Name",
    "form.petname.ph": "e.g. Bruno",
    "form.pettype": "Pet Type",
    "form.pettype.ph": "Select...",
    "form.service": "Service Needed *",
    "form.service.ph": "Choose a service...",
    "form.msg": "Describe the Problem",
    "form.msg.ph": "Describe your pet's condition or any specific concerns...",
    "form.submit": "📅 Request Appointment",
    "form.call": "Or call us directly:",
    "form.success.title": "Appointment Request Sent!",
    "form.success.desc": "Dr. Foysal will contact you shortly to confirm your visit.",
    "form.success.urgent": "For urgent cases, please call or WhatsApp directly:",
    "opt.dog": "Dog 🐕",
    "opt.cat": "Cat 🐈",
    "opt.bird": "Bird 🦜",
    "opt.rabbit": "Rabbit 🐇",
    "opt.other": "Other",
    "svc.consultation": "General Consultation",
    "svc.surgery": "Surgery / Operation",
    "svc.vaccination": "Vaccination",
    "svc.online": "Online Consultation",
    "svc.deworming": "Deworming",
    "svc.other": "Other",

    // Footer
    "footer.desc": "Expert veterinary consultation and surgery for pet animals. Located in Mohammadpur, Dhaka. Always open for your pets.",
    "footer.services": "Services",
    "footer.contact": "Contact",
    "footer.copyright": "© 2026 Vet Consult · Dr. Foysal Kabir. All rights reserved.",
  },

  bn: {
    // Navbar
    "nav.services": "সেবাসমূহ",
    "nav.about": "আমাদের সম্পর্কে",
    "nav.doctor": "ডাক্তার",
    "nav.contact": "যোগাযোগ",
    "nav.book": "অ্যাপয়েন্টমেন্ট নিন",
    "nav.subtitle": "ডা. ফয়সাল কবীর",

    // Hero
    "hero.badge": "বিভিসি নিবন্ধন নং ৯৭৭৪ · সর্বদা খোলা",
    "hero.title": "ভেট কনসাল্ট",
    "hero.degree": "বিএসসি ভেট সায়েন্স ও এএইচ (এসএইউ) | সার্জারিতে এমএস ফেলো (এসএইউ)",
    "hero.role": "নিবন্ধিত পশুচিকিৎসক · পোষা প্রাণীর পরামর্শদাতা ও সার্জন",
    "hero.desc": "আপনার প্রিয় পোষা প্রাণীর জন্য বিশেষজ্ঞ পশুচিকিৎসা, অস্ত্রোপচার ও সম্পূর্ণ সেবা। মোহাম্মদপুর, ঢাকায় অবস্থিত — সর্বদা আপনার পোষা প্রাণীর জন্য উপলব্ধ।",
    "hero.book": "📅 অ্যাপয়েন্টমেন্ট নিন",
    "hero.whatsapp": "💬 হোয়াটসঅ্যাপ করুন",
    "hero.open": "সর্বদা খোলা",
    "hero.location": "মোহাম্মদপুর, ঢাকা",
    "hero.surgery": "অস্ত্রোপচার ও পরামর্শ",
    "hero.online": "অনলাইন পরামর্শ পাওয়া যায়",

    // Services
    "services.badge": "আমাদের সেবা",
    "services.title1": "বিশেষজ্ঞ সেবা",
    "services.title2": "প্রতিটি পোষা প্রাণীর জন্য",
    "services.desc": "নিয়মিত স্বাস্থ্য পরীক্ষা থেকে শুরু করে জটিল অস্ত্রোপচার পর্যন্ত — আপনার প্রিয় পোষা প্রাণীর জন্য পেশাদার পশুচিকিৎসা সেবা।",
    "services.also": "আরও সেবা পাওয়া যায়",
    "services.book": "বুক করুন →",
    "s1.title": "সাধারণ পরামর্শ",
    "s1.desc": "কুকুর, বিড়াল ও অন্যান্য পোষা প্রাণীর সম্পূর্ণ স্বাস্থ্য পরীক্ষা। অসুস্থতা, আঘাত ও দীর্ঘমেয়াদী রোগের চিকিৎসা।",
    "s1.badge": "সর্বাধিক জনপ্রিয়",
    "s2.title": "অস্ত্রোপচার ও অপারেশন",
    "s2.desc": "ডা. ফয়সাল কবীরের (সার্জারিতে এমএস ফেলো) বিশেষজ্ঞ অস্ত্রোপচার সেবা। সফট টিস্যু সার্জারি, অর্থোপেডিক ও জরুরি অপারেশন।",
    "s3.title": "টিকাদান ও প্রতিরোধ",
    "s3.desc": "কুকুর ও বিড়ালের সম্পূর্ণ টিকার সময়সূচি। র্যাবিস, ডিস্টেম্পার, পার্ভোভাইরাস ও অন্যান্য প্রয়োজনীয় টিকা।",
    "s4.title": "অনলাইন পরামর্শ",
    "s4.desc": "ক্লিনিকে আসতে পারছেন না? হোয়াটসঅ্যাপ বা ফোনে বিশেষজ্ঞ পরামর্শ নিন। বাংলাদেশের যেকোনো স্থান থেকে।",
    "s4.badge": "এখনই পাওয়া যাচ্ছে",
    "extra.dental": "দাঁতের চিকিৎসা",
    "extra.xray": "এক্স-রে ও ইমেজিং",
    "extra.deworm": "কৃমিনাশক",
    "extra.neuter": "নিউটারিং / স্পেয়িং",
    "extra.wound": "ক্ষতের চিকিৎসা",
    "extra.lab": "ল্যাব পরীক্ষা",

    // Why Us
    "why.badge": "কেন ভেট কনসাল্ট?",
    "why.title1": "যত্নশীল সেবা,",
    "why.title2": "বিশেষজ্ঞ হাত",
    "why.p1": "ভেট কনসাল্ট মোহাম্মদপুর, ঢাকার একটি নিবেদিতপ্রাণ পশুচিকিৎসালয়। ডা. ফয়সাল কবীরের নেতৃত্বে আমরা ক্লিনিক্যাল দক্ষতা ও প্রাণীদের প্রতি ভালোবাসা একত্রিত করে সর্বোত্তম সেবা প্রদান করি।",
    "why.p2": "নিয়মিত টিকা, জরুরি অস্ত্রোপচার, বা অনলাইন পরামর্শ — যাই হোক, আমরা সর্বদা আপনার ও আপনার পোষা প্রাণীর পাশে আছি।",
    "why.cta1": "পরামর্শ বুক করুন →",
    "why.cta2": "💬 হোয়াটসঅ্যাপ",
    "why.r1.title": "সর্বদা খোলা",
    "why.r1.desc": "আমাদের ক্লিনিক ২৪/৭ খোলা — কারণ জরুরি পরিস্থিতি সময় মেনে চলে না। আপনার পোষা প্রাণীর স্বাস্থ্য আমাদের সর্বোচ্চ অগ্রাধিকার।",
    "why.r2.title": "যোগ্যতাসম্পন্ন সার্জন",
    "why.r2.desc": "ডা. ফয়সাল কবীর এসএইউ থেকে সার্জারিতে এমএস ফেলোশিপ প্রাপ্ত, যা আপনার পোষা প্রাণীর জন্য বিশেষজ্ঞ অস্ত্রোপচার সেবা নিশ্চিত করে।",
    "why.r3.title": "নিবন্ধিত চিকিৎসক",
    "why.r3.desc": "বিভিসি নিবন্ধিত (নিবন্ধন নং ৯৭৭৪) — বাংলাদেশের সর্বোচ্চ পেশাদার পশুচিকিৎসা মানদণ্ড অনুসরণকারী।",
    "why.r4.title": "অনলাইন পরামর্শ",
    "why.r4.desc": "বাংলাদেশের যেকোনো স্থান থেকে হোয়াটসঅ্যাপ, ফোন বা ভিডিও কলে বিশেষজ্ঞ পরামর্শ নিন।",
    "why.r5.title": "সব ধরনের পোষা প্রাণী",
    "why.r5.desc": "আমরা কুকুর, বিড়াল, খরগোশ, পাখি ও আরও অনেক প্রাণীর যত্ন নিই। প্রতিটি প্রাণী পেশাদার চিকিৎসার দাবিদার।",
    "why.r6.title": "সম্পূর্ণ চিকিৎসা",
    "why.r6.desc": "নিয়মিত পরীক্ষা ও টিকা থেকে শুরু করে জটিল অস্ত্রোপচার পর্যন্ত — একটি ছাদের নিচে সম্পূর্ণ পশুচিকিৎসা সেবা।",

    // Doctor
    "doc.badge": "ডাক্তারের সাথে পরিচয়",
    "doc.title1": "আপনার পোষা প্রাণীর",
    "doc.title2": "বিশ্বস্ত বিশেষজ্ঞ",
    "doc.name": "ডা. ফয়সাল কবীর",
    "doc.role": "পরামর্শদাতা ও সার্জন — ভেট কনসাল্ট",
    "doc.c1": "বিএসসি ভেট সায়েন্স ও এএইচ — শেরেবাংলা কৃষি বিশ্ববিদ্যালয় (এসএইউ)",
    "doc.c2": "সার্জারিতে এমএস ফেলো — শেরেবাংলা কৃষি বিশ্ববিদ্যালয় (এসএইউ)",
    "doc.c3": "নিবন্ধিত পশুচিকিৎসক · বিভিসি নিবন্ধন নং ৯৭৭৪",
    "doc.c4": "কম্প্যানিয়ন অ্যানিমাল মেডিসিন ও সার্জারিতে বিশেষজ্ঞ (কুকুর, বিড়াল ও আরও)",
    "doc.about": "ডা. ফয়সাল কবীর পশু চিকিৎসাবিজ্ঞান ও অস্ত্রোপচারে গভীর দক্ষতা নিয়ে প্রতিটি রোগীর সেবায় নিয়োজিত। প্রাণীর কল্যাণে আন্তরিক এবং প্রমাণভিত্তিক চিকিৎসায় প্রতিশ্রুতিবদ্ধ এই চিকিৎসক ঢাকায় শতাধিক পোষা প্রাণীর মালিককে সুস্থ ও সুখী জীবন নিশ্চিত করতে সাহায্য করেছেন।",
    "doc.wa": "💬 ডা. ফয়সালকে হোয়াটসঅ্যাপ করুন",
    "doc.book": "📅 ভিজিট বুক করুন",

    // Testimonials
    "test.badge": "রোগীদের মতামত",
    "test.title1": "সুখী পোষা প্রাণী,",
    "test.title2": "সুখী মালিক",
    "test.desc": "ঢাকার পোষা প্রাণীর মালিকরা ডা. ফয়সাল কবীর ও ভেট কনসাল্ট সম্পর্কে কী বলছেন।",
    "t1.name": "রহিম উদ্দিন",
    "t1.pet": "টমির (কুকুর) মালিক",
    "t1.text": "ডা. ফয়সাল আমার ল্যাব্রাডর টমিকে গুরুতর সংক্রমণ থেকে সুস্থ করে তুলেছেন। তিনি সতর্ক, যত্নশীল এবং ফলো-আপ প্রশ্নের জন্য সর্বদা হোয়াটসঅ্যাপে পাওয়া যায়। অত্যন্ত সুপারিশযোগ্য!",
    "t2.name": "নুসরাত জাহান",
    "t2.pet": "মিঠুর (বিড়াল) মালিক",
    "t2.text": "আমার বিড়ালের জটিল অস্ত্রোপচার ডা. ফয়সাল দক্ষতার সাথে সম্পন্ন করেছেন। ক্লিনিক পরিষ্কার, ডাক্তার পেশাদার, এবং ২৪/৭ উপলব্ধতা মনে অনেক শান্তি দেয়।",
    "t3.name": "আরিফ হোসেন",
    "t3.pet": "ব্রুনোর (কুকুর) মালিক",
    "t3.text": "নিঃসন্দেহে মোহাম্মদপুরের সেরা পশুচিকিৎসক। ব্রুনোর টিকা ও কৃমিনাশকের সময়সূচি সর্বদা নিখুঁতভাবে পরিচালনা করা হয়। ব্যস্ত দিনগুলোতে অনলাইন পরামর্শ সত্যিই অনেক কাজে লাগে।",
    "t4.name": "ফাতেমা খানম",
    "t4.pet": "মিমির (বিড়াল) মালিক",
    "t4.text": "ডা. ফয়সাল সত্যিকারের প্রাণী কল্যাণে আগ্রহী। তিনি সবকিছু স্পষ্টভাবে বুঝিয়ে দেন এবং কখনো তাড়াহুড়ো করেন না। মিমি এখানে সর্বোত্তম যত্নে থাকে।",
    "t5.name": "তানভীর আহমেদ",
    "t5.pet": "রেক্সের (কুকুর) মালিক",
    "t5.text": "আমি মধ্যরাতে জরুরি কারণে ফোন করেছিলাম এবং ডা. ফয়সাল তাৎক্ষণিকভাবে সাড়া দিয়েছিলেন। এই ধরনের নিষ্ঠা বিরল। রেক্স তার বিশেষজ্ঞ সেবার কারণে সম্পূর্ণ সুস্থ হয়ে উঠেছে।",
    "t6.name": "সাদিয়া ইসলাম",
    "t6.pet": "কিকির (পাখি) মালিক",
    "t6.text": "ঢাকার কমসংখ্যক পশুচিকিৎসকের মধ্যে একজন যিনি পাখির সঠিক চিকিৎসা করেন। ডা. ফয়সালের তত্ত্বাবধানে কিকির স্বাস্থ্য উল্লেখযোগ্যভাবে উন্নত হয়েছে।",

    // Contact
    "contact.badge": "আমাদের কাছে আসুন",
    "contact.title1": "আমরা",
    "contact.title2": "সর্বদা খোলা",
    "contact.desc": "যেকোনো সময় আসুন বা আগে থেকে অ্যাপয়েন্টমেন্ট নিন। জরুরি ক্ষেত্রে সরাসরি ফোন বা হোয়াটসঅ্যাপ করুন — আমরা দ্রুত সাড়া দিই।",
    "contact.addr.label": "ঠিকানা",
    "contact.addr.value": "১০/৭, ব্লক-এ, ইকবাল রোড (হোলি ফ্লাওয়ার স্কুলের বিপরীতে), গ্রিন হোমস ১ম তলা, ফ্ল্যাট এ-২, মোহাম্মদপুর, ঢাকা-১২০৭",
    "contact.phone.label": "ফোন",
    "contact.alt.label": "বিকল্প নম্বর",
    "contact.wa.label": "হোয়াটসঅ্যাপ",
    "contact.email.label": "ইমেইল",
    "contact.hours.label": "সময়",
    "contact.hours.value": "সর্বদা খোলা — ২৪/৭",
    "contact.fb": "ফেসবুকে ফলো করুন",
    "form.title": "অ্যাপয়েন্টমেন্ট বুক করুন",
    "form.desc": "ফর্মটি পূরণ করুন, আমরা দ্রুত আপনার ভিজিট নিশ্চিত করব।",
    "form.name": "আপনার নাম *",
    "form.name.ph": "আপনার পূর্ণ নাম",
    "form.phone": "ফোন / হোয়াটসঅ্যাপ *",
    "form.phone.ph": "০১XXXXXXXXX",
    "form.petname": "পোষা প্রাণীর নাম",
    "form.petname.ph": "যেমন: ব্রুনো",
    "form.pettype": "প্রাণীর ধরন",
    "form.pettype.ph": "বেছে নিন...",
    "form.service": "প্রয়োজনীয় সেবা *",
    "form.service.ph": "সেবা বেছে নিন...",
    "form.msg": "সমস্যার বিবরণ",
    "form.msg.ph": "আপনার পোষা প্রাণীর অবস্থা বা যেকোনো উদ্বেগ বর্ণনা করুন...",
    "form.submit": "📅 অ্যাপয়েন্টমেন্টের অনুরোধ করুন",
    "form.call": "অথবা সরাসরি কল করুন:",
    "form.success.title": "অ্যাপয়েন্টমেন্টের অনুরোধ পাঠানো হয়েছে!",
    "form.success.desc": "ডা. ফয়সাল শীঘ্রই আপনার ভিজিট নিশ্চিত করতে যোগাযোগ করবেন।",
    "form.success.urgent": "জরুরি ক্ষেত্রে সরাসরি ফোন বা হোয়াটসঅ্যাপ করুন:",
    "opt.dog": "কুকুর 🐕",
    "opt.cat": "বিড়াল 🐈",
    "opt.bird": "পাখি 🦜",
    "opt.rabbit": "খরগোশ 🐇",
    "opt.other": "অন্যান্য",
    "svc.consultation": "সাধারণ পরামর্শ",
    "svc.surgery": "অস্ত্রোপচার",
    "svc.vaccination": "টিকাদান",
    "svc.online": "অনলাইন পরামর্শ",
    "svc.deworming": "কৃমিনাশক",
    "svc.other": "অন্যান্য",

    // Footer
    "footer.desc": "পোষা প্রাণীর জন্য বিশেষজ্ঞ পশুচিকিৎসা পরামর্শ ও অস্ত্রোপচার সেবা। মোহাম্মদপুর, ঢাকায় অবস্থিত। সর্বদা আপনার পোষা প্রাণীর জন্য খোলা।",
    "footer.services": "সেবাসমূহ",
    "footer.contact": "যোগাযোগ",
    "footer.copyright": "© ২০২৬ ভেট কনসাল্ট · ডা. ফয়সাল কবীর। সর্বস্বত্ব সংরক্ষিত।",
  },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>("en");

  const toggle = () => setLang((prev) => (prev === "en" ? "bn" : "en"));

  const t = (key: string): string => translations[lang][key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
